### ISSUE TITLE
[BUG]: Unable to run any tests

### ISSUE THREAD

**Issue by AgrPaavan** [ShaunSHamilton/web3#94]
### Issue/Experience
I started the course and just in the first lesson where you cd into a folder, none of my tests were passing.

### Output of running `node tooling/camper-info.js` from the workspace root
```
🔵 INFO:   Project:  learn-digital-ledgers-by-building-a-blockchain
🔵 INFO:   Lesson Number:  1
🔵 INFO:   Curriculum Version:  0.1.3
🔵 INFO:   freeCodeCamp - Courses:  undefined
🔵 INFO:   Commit:  c1ef015 chore: update freecodecamp-os to 1.8.3 (#92)

🔵 INFO:   OS Info: 
    Architecture: x64
    Platform: linux
    Release: 5.15.90.1-microsoft-standard-WSL2
    Type: Linux
```

### Output of freeCodeCamp: Run Course terminal
```🔵 INFO:  2023-04-30 12:12:42 Listening on port 8080
🔵 INFO:  2023-04-30 12:12:44 Watching for file changes on /workspace/web3-curriculum
🔴 ERROR:  2023-04-30 12:12:48 Test #2: Error: Could not find /workspace/web3-curriculum/.logs/.cwd.log
    at Object.getCWD (file:///workspace/web3-curriculum/node_modules/@freecodecamp/freecodecamp-os/.freeCodeCamp/tooling/test-utils.js:133:11)
    at async eval (eval at <anonymous> (file:///workspace/web3-curriculum/node_modules/@freecodecamp/freecodecamp-os/.freeCodeCamp/tooling/test.js:94:35), <anonymous>:2:17)
    at async file:///workspace/web3-curriculum/node_modules/@freecodecamp/freecodecamp-os/.freeCodeCamp/tooling/test.js:94:29
    at async Promise.allSettled (index 1)
    at async runTests (file:///workspace/web3-curriculum/node_modules/@freecodecamp/freecodecamp-os/.freeCodeCamp/tooling/test.js:122:22)
    at async FSWatcher.<anonymous> (file:///workspace/web3-curriculum/node_modules/@freecodecamp/freecodecamp-os/.freeCodeCamp/tooling/hot-reload.js:51:9)
🔴 ERROR:  2023-04-30 12:13:21 Test #2: Error: Could not find /workspace/web3-curriculum/.logs/.cwd.log
    at Object.getCWD (file:///workspace/web3-curriculum/node_modules/@freecodecamp/freecodecamp-os/.freeCodeCamp/tooling/test-utils.js:133:11)
    at async eval (eval at <anonymous> (file:///workspace/web3-curriculum/node_modules/@freecodecamp/freecodecamp-os/.freeCodeCamp/tooling/test.js:94:35), <anonymous>:2:17)
    at async file:///workspace/web3-curriculum/node_modules/@freecodecamp/freecodecamp-os/.freeCodeCamp/tooling/test.js:94:29
    at async Promise.allSettled (index 1)
    at async runTests (file:///workspace/web3-curriculum/node_modules/@freecodecamp/freecodecamp-os/.freeCodeCamp/tooling/test.js:122:22)
    at async Object.handleRunTests [as run-tests] (file:///workspace/web3-curriculum/node_modules/@freecodecamp/freecodecamp-os/.freeCodeCamp/tooling/server.js:48:3)
🔴 ERROR:  2023-04-30 12:14:59 Test #2: Error: Could not find /workspace/web3-curriculum/.logs/.cwd.log
    at Object.getCWD (file:///workspace/web3-curriculum/node_modules/@freecodecamp/freecodecamp-os/.freeCodeCamp/tooling/test-utils.js:133:11)
    at async eval (eval at <anonymous> (file:///workspace/web3-curriculum/node_modules/@freecodecamp/freecodecamp-os/.freeCodeCamp/tooling/test.js:94:35), <anonymous>:2:17)
    at async file:///workspace/web3-curriculum/node_modules/@freecodecamp/freecodecamp-os/.freeCodeCamp/tooling/test.js:94:29
    at async Promise.allSettled (index 1)
    at async runTests (file:///workspace/web3-curriculum/node_modules/@freecodecamp/freecodecamp-os/.freeCodeCamp/tooling/test.js:122:22)
    at async Object.handleRunTests [as run-tests] (file:///workspace/web3-curriculum/node_modules/@freecodecamp/freecodecamp-os/.freeCodeCamp/tooling/server.js:48:3)
```

**Comment by leesper** [comment]
The same problem, I shutdown all my terminals and reopen again, doesn't work

**Comment by leesper** [comment]
![image](https://user-images.githubusercontent.com/5260728/235418175-03a001ae-6108-4920-9639-9d73a533c017.png)

@AgrPaavan Try to add a bash by clicking the + symbol in the right bottom of the vs code and it works

**Comment by AgrPaavan** [comment]
Hey @ShaunSHamilton I just pulled and rebuilt a container from your branch and I still seem to be getting the same error.
```
: No such file or directory
BashRC Sourced
root@70b27df2fe92:/workspace/web3-curriculum# cd . && NODE_ENV=production node ./node_modules/@freecodecamp/freecodecamp-os/.freeCodeCamp/tooling/server.js
🔵 INFO:  2023-05-01 11:25:01 Listening on port 8080
🔵 INFO:  2023-05-01 11:25:07 Watching for file changes on /workspace/web3-curriculum
🔴 ERROR:  2023-05-01 11:25:10 Test #2: Error: Could not find /workspace/web3-curriculum/.logs/.cwd.log
    at Object.getCWD (file:///workspace/web3-curriculum/node_modules/@freecodecamp/freecodecamp-os/.freeCodeCamp/tooling/test-utils.js:133:11)
    at async eval (eval at <anonymous> (file:///workspace/web3-curriculum/node_modules/@freecodecamp/freecodecamp-os/.freeCodeCamp/tooling/test.js:94:35), <anonymous>:2:17)
    at async file:///workspace/web3-curriculum/node_modules/@freecodecamp/freecodecamp-os/.freeCodeCamp/tooling/test.js:94:29
    at async Promise.allSettled (index 1)
    at async runTests (file:///workspace/web3-curriculum/node_modules/@freecodecamp/freecodecamp-os/.freeCodeCamp/tooling/test.js:122:22)
    at async FSWatcher.<anonymous> (file:///workspace/web3-curriculum/node_modules/@freecodecamp/freecodecamp-os/.freeCodeCamp/tooling/hot-reload.js:51:9)
🔴 ERROR:  2023-05-01 11:25:19 Test #2: Error: Could not find /workspace/web3-curriculum/.logs/.cwd.log
    at Object.getCWD (file:///workspace/web3-curriculum/node_modules/@freecodecamp/freecodecamp-os/.freeCodeCamp/tooling/test-utils.js:133:11)
    at async eval (eval at <anonymous> (file:///workspace/web3-curriculum/node_modules/@freecodecamp/freecodecamp-os/.freeCodeCamp/tooling/test.js:94:35), <anonymous>:2:17)
    at async file:///workspace/web3-curriculum/node_modules/@freecodecamp/freecodecamp-os/.freeCodeCamp/tooling/test.js:94:29
    at async Promise.allSettled (index 1)
    at async runTests (file:///workspace/web3-curriculum/node_modules/@freecodecamp/freecodecamp-os/.freeCodeCamp/tooling/test.js:122:22)
    at async Object.handleRunTests [as run-tests] (file:///workspace/web3-curriculum/node_modules/@freecodecamp/freecodecamp-os/.freeCodeCamp/tooling/server.js:48:3)
🔴 ERROR:  2023-05-01 11:25:34 Test #2: Error: Could not find /workspace/web3-curriculum/.logs/.cwd.log
    at Object.getCWD (file:///workspace/web3-curriculum/node_modules/@freecodecamp/freecodecamp-os/.freeCodeCamp/tooling/test-utils.js:133:11)
    at async eval (eval at <anonymous> (file:///workspace/web3-curriculum/node_modules/@freecodecamp/freecodecamp-os/.freeCodeCamp/tooling/test.js:94:35), <anonymous>:2:17)
    at async file:///workspace/web3-curriculum/node_modules/@freecodecamp/freecodecamp-os/.freeCodeCamp/tooling/test.js:94:29
    at async Promise.allSettled (index 1)
    at async runTests (file:///workspace/web3-curriculum/node_modules/@freecodecamp/freecodecamp-os/.freeCodeCamp/tooling/test.js:122:22)
    at async Object.handleRunTests [as run-tests] (file:///workspace/web3-curriculum/node_modules/@freecodecamp/freecodecamp-os/.freeCodeCamp/tooling/server.js:48:3)
```

**Comment by ShaunSHamilton** [comment]
Re-opening until we can confirm the reproducability of this.

**Comment by AgrPaavan** [comment]
Just rebuild the container without cache after pulling the latest commit. Still get the same error.

**Comment by moT01** [comment]
Looks like there's a few potential solutions here: https://stackoverflow.com/questions/51820921/vscode-integrated-terminal-doesnt-load-bashrc-or-bash-profile

**Comment by ShaunSHamilton** [comment]
I am unable to reproduce this.

**Comment by AgrPaavan** [comment]
> Looks like there's a few potential solutions here: https://stackoverflow.com/questions/51820921/vscode-integrated-terminal-doesnt-load-bashrc-or-bash-profile

Hey I went through the page and did what it recommended but am still constantly getting the same issue.

**Comment by duartenunes86** [comment]
I have the same error...nothing works

**Comment by duartenunes86** [comment]
and I have not AppData folder

**Comment by duartenunes86** [comment]
I found the Appdata folder....I added the thing but it still doesnt work

**Comment by kabirrajsingh** [comment]
Any fix yet?

**Comment by ShaunSHamilton** [comment]
@kabirrajsingh I have not been able to reproduce any issue here. So, unless someone who can reproduce it can submit a path, you should try another method for the curriculum (e.g. Gitpod)

**Comment by kabirrajsingh** [comment]
How do I access  the course using GitPod?
Never used it

**Comment by ShaunSHamilton** [comment]
@kabirrajsingh 
Either:
a) Download the Gitpod browser extension for easiest access: https://chrome.google.com/webstore/detail/gitpod-always-ready-to-co/dodmmooeoklaejobgleioelladacbeki
b) Navigate to this link: https://gitpod.io/#https://github.com/freeCodeCamp/web3-curriculum

Then:
1) Connect your GitHub account to Gitpod (it is free for 50 hours per month)
2) The course should open, and you can run `freeCodeCamp: Run Course`

https://github.com/freeCodeCamp/web3-curriculum/assets/51722130/7ce1f81f-08f7-4be6-8f9e-d8cc4bd0d10c
